version: '3'

services:
    app:
        container_name: blog-app
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./zeblog/:/var/www/
        networks:
            - blog

    database:
        container_name: blog-database
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - blog

    phpmyadmin:
        container_name: blog-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=database
        networks:
            - blog

volumes:
    db-data:

networks:
    blog:
